export const TODO_SCREEN_TEXT = {
  titleTodos: "My Todos",
  titleCategories: "Categories",
  addButton: "Add",
  cancelButton: "Cancel",
  todoTitlePlaceholder: "Todo title",
  todoDescriptionPlaceholder: "Description (optional)",
  todoCompleteByPlaceholder: "Complete by date/time (optional)",
  todoCategoryLabel: "Select Category",
  addTodoButton: "Add Todo",
  categoryNamePlaceholder: "Category name",
  categoryColorLabel: "Select Color",
  addCategoryButton: "Add Category",
  noTodosMessage: "No todos yet. Add one above!",
  noCategoriesMessage: "No categories yet. Create one first!",
  deleteTodoTitle: "Delete Todo",
  deleteTodoBody: "Are you sure you want to delete this todo?",
  deleteCategoryTitle: "Delete Category",
  deleteCategoryBody: "Are you sure you want to delete this category?",
  deleteButtonText: "Delete",
  loadingText: "Loading...",
  errorLoadingTodos: "Failed to load todos",
  errorLoadingCategories: "Failed to load categories",
  errorAddingTodo: "Failed to add todo",
  errorTogglingTodo: "Failed to update todo",
  errorDeletingTodo: "Failed to delete todo",
  errorAddingCategory: "Failed to add category",
  errorDeletingCategory: "Failed to delete category",
  errorTitleRequired: "Please enter a title",
  errorCategoryRequired: "Please select a category",
  errorCategoryNameRequired: "Please enter a category name",
};

export const TODO_COLORS = [
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#FFA07A",
  "#98D8C8",
  "#F7DC6F",
  "#BB8FCE",
  "#85C1E2",
];
